name: manual-deploy-docs

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Please enter a pull request number'
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: gh pr checkout ${{ inputs.pr_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: "18"
    - run: yarn install
    - name: Build en-US
      env:
        DOC_LANG: en-US
      run: yarn build
    - name: Build fr-FR
      env:
        DOC_LANG: fr-FR
      run: yarn build
    - name: Build zh-CN
      env:
        DOC_LANG: zh-CN
      run: yarn build
    - name: Build ja-JP
      env:
        DOC_LANG: ja-JP
      run: yarn build
    - name: Set tags
      id: set-tags
      run: |
        echo "::set-output name=tags::pr-${{ inputs.pr_number }}"
    - name: copy files via ssh - ${{ steps.set-tags.outputs.tags }}
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.CN_HOST }}
        username: ${{ secrets.CN_USERNAME }}
        key: ${{ secrets.CN_KEY }}
        port: ${{ secrets.CN_PORT }}
        source: "dist/*"
        target: ${{ secrets.CN_TARGET }}/${{ steps.set-tags.outputs.tags }}
